### ISSUE TITLE
What can be done to get better VSCode API support for this extension?

### ISSUE THREAD

**Issue by TonyGravagno** [ctf0/vscode-save-editor-layout#4]
It's kinda crappy that your VSCode [API request](https://github.com/microsoft/vscode/issues/88612) was closed. A 60 day wait period is nuts in a world where we discover utilities over a period of years. As an example, I just re-setup my 3 monitors so that one is in portrait and the other two are in landscape. I manipulate my VSCode layout so that each monitor has an editor : I split-right with one editor in portrait. Then I split the first column down and display the top in one monitor which is physically above the monitor below. Then I adjust all windows to give the feel that each is completely independent with it's own tabs, scroll, and map.

Having just setup this configuration, just today I started to search for a solution to save the layout, and immediately found this extension. Of course I want to save this layout with your extension - but we can't because of some arbitrary 60 day limit for +1's on the VSC repo before they close a ticket.

Are you aware of any recent developments in this area? Is there anything else that we (community) can do to get some traction on this? Opening a new ticket in the other repo will be futile if the same process is followed with no support.

Thanks for the effort. I hope that over time I can help in some way.

**Comment by ctf0** [comment]
unfortunately there is no way around that i know of, i've tried my best with the arrow functionality but sadly its not a complete solution, i would try again with creating a new ticket and hopefully this time it get some attention but with how the vscode team is currently prioritizing new features, i wouldn't keep my hopes high.

still am open to new ideas until the api is in place.

**Comment by dandavison** [comment]
Thanks for the effort on this extension nevertheless! I am also looking forward to more sophisticated support for saving custom layouts in VSCode: after all, something like that is standard in vim, emacs, tmux, screen, and doubtless other editors/IDEs.

**Comment by Krysl** [comment]
https://github.com/microsoft/vscode/blame/af5ef24b527beac6d2097abb924b353c1926d873/src/vs/workbench/browser/parts/editor/editorCommands.ts#L339-L351
A command(`vscode.getEditorLayout`) that just came out a month ago.
```ts
const editorGroupLayout: EditorGroupLayout = await vscode.commands.executeCommand('vscode.getEditorLayout');
```
I tried it and found that it can be used on the insiders version of vscode.

**Comment by ctf0** [comment]
@Krysl can u make a PR with the changes needed ?

**Comment by Krysl** [comment]
@ctf0

> @Krysl can u make a PR with the changes needed ?

But I think it needs to be changed a bit more:
- buttons/commands not needed:
    - column increase/subtract
    - open editor in below/right group
    - set layout orintation to vertical/horizontal

If I were to develop, I would probably delete a lot of code

**Comment by ctf0** [comment]
@Krysl  yes understandable, those were a temp solutions for the limitation of the api

**Comment by ctf0** [comment]
plz check latest release, the limitations should be fixed now, thanks @Krysl for the headsup.

**Comment by Krysl** [comment]
@ctf0

so quickly!
I still have a lot of code to write.
![saveLayout2](https://user-images.githubusercontent.com/5905801/229280736-d994837c-1df9-4dcb-b5b0-600fa40b8107.gif)

**Comment by ctf0** [comment]
@Krysl if u have a different enhancements, plz open a new ticket

**Comment by TonyGravagno** [comment]
Verified that it's working. Congratulations!!! And thank you!!!
